

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <ctype.h>
#include <unistd.h>
#include <errno.h>
#include <time.h>

#include <time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <termios.h>

#include "Diablo_Types4D.h"			// defines data types used by the 4D Routines
#include "Diablo_const4D.h"			// defines for 4dgl constants, generated by conversion of 4DGL constants to target language
//#include "picasoSerial.h"

#define   Err4D_OK              0
#define   Err4D_Timeout         1
#define   Err4D_NAK		2               // other than ACK received


// 4D Global variables
int    cPort;                                   // comp port handle, used by Intrinsic routines
int    Error4D ;  				// Error indicator,  used and set by Intrinsic routines
unsigned char Error4D_Inv ;                     // Error byte returned from com port, onl set if error = Err_Invalid
int Error_Abort4D ;                             // if true routines will abort when detecting an error
int TimeLimit4D ;                               // time limit in ms for total serial command duration, 2000 (2 seconds) should be adequate for most commands
                                                // assuming a reasonable baud rate AND low latency AND 0 for the Serial Delay Parameter
                                                // temporary increase might be required for very long (bitmap write, large image file opens)
int(*Callback4D) (int, unsigned char) ;         // or indeterminate (eg file_exec, file_run, file_callFunction)  commands

/*
 * Start of 4D Intrinsic Routines
*/

void WriteBytes(unsigned char *psOutput, int nCount)
{
    int iOut;
    // Quick return if no device
    if (cPort < 0)
    {
        Error4D = Err4D_OK;
        return;
    }
    iOut = write(cPort, psOutput, nCount);
    if (iOut < 0)
    {
        printf("write error %d %s\n", errno, strerror(errno));
    }
    if (iOut != nCount)
        printf("Write incomplete!\n");
    return;
}

void WriteChars(unsigned char *psOutput)
{
    // Include NULL in output
    WriteBytes(psOutput, strlen((char *)psOutput) + 1);
    return;
}

void WriteWords(WORD * Source, int Size)
{
 	WORD wk ;
	int i ;
	for (i = 0; i < Size; i++)
	{
		wk = *Source++ ;
		wk = (wk >> 8) + (wk << 8) ;
		WriteBytes((unsigned char *)&wk, 2);
	}
}

// Return system time in ms
DWORD GetTickCount(void)
{
    struct timespec ttime;
    clock_gettime(CLOCK_MONOTONIC, &ttime);
    return (ttime.tv_sec * 1000) + (ttime.tv_nsec / 1000000);
}

// read string from the serial port
// return code:
//   >= 0 = number of characters read
//   -1 = read failed
int ReadSerPort(unsigned char *psData, int iMax)
{
    int iIn, iLeft, iIdx;
    DWORD sttime;

    // Quick return if no device
    if (cPort < 0)
    {
        Error4D = Err4D_OK;
        *psData = '\0';
        return iMax;
    }
    iIdx = 0;
    iLeft = iMax;
    sttime = GetTickCount();
    while (iLeft > 0)
    {
        iIn = read(cPort, &psData[iIdx], iLeft);
        if (iIn < 0)
        {
            if (errno == EAGAIN)
            {
                // Would block -- check timeout
                if ((GetTickCount() - sttime) >= TimeLimit4D)
                {
                    //printf("timeout - %d read\n", iIdx);
                    return -(iIdx + 10000);
                }
                usleep(100);  // Wait .1ms
                continue;
            }
            printf("Read error %d %s\n", errno, strerror(errno));
            return -1;
        }
        // Anything?
        if (iIn > 0)
        {
            // Calc remaining
            iLeft -= iIn;
            iIdx += iIn;
        }
        // Keep reading
    }

    return iMax;
}

void getbytes(unsigned char *data, int size)
{
 	int readc;
	readc = ReadSerPort(data, size) ;
	if ((readc != size)
	    && (Callback4D != NULL) )
	{
		Error4D = Err4D_Timeout ;
		Callback4D(Error4D, Error4D_Inv) ;
 	}
}

void GetAck(void)
{
	int readc;
	unsigned char readx ;
	Error4D = Err4D_OK ;
    // Quick return if no device
    if (cPort < 0)
    {
        Error4D = Err4D_OK;
        return;
    }
   	readc = ReadSerPort(&readx, 1) ;

	if (readc != 1)
    {
		Error4D = Err4D_Timeout ;
        if (Callback4D != NULL)
            Callback4D(Error4D, Error4D_Inv) ;
    }
	else if (readx != 6)
	{
	   	Error4D     = Err4D_NAK ;
	   	Error4D_Inv = readx ;
		if (Callback4D != NULL)
	 		Callback4D(Error4D, Error4D_Inv) ;
	}

    return;
}


WORD GetWord(void)
{
 	int readc;
 	unsigned char readx[2] ;

 	if (Error4D != Err4D_OK)
 		return 0 ;

    readc = ReadSerPort(&readx[0], 2) ;

	if (readc != 2)
	{
		Error4D  = Err4D_Timeout ;
		if (Callback4D != NULL)
	 		return Callback4D(Error4D, Error4D_Inv) ;
		return -Error4D ;
	}
	else
		return readx[0] << 8 | readx[1] ;
}

void getString(unsigned char *outStr, int strLen)
{
 	int readc;

 	if (Error4D != Err4D_OK)
	{
		outStr[0] = '\0' ;
 		return ;
	}

	readc = ReadSerPort(outStr, strLen) ;

	if (readc != strLen)
	{
		Error4D  = Err4D_Timeout ;
		if (Callback4D != NULL)
	 		Callback4D(Error4D, Error4D_Inv) ;
	}

    // Append EOS
	outStr[readc] = '\0' ;

	return;
}

WORD GetAckResp(void)
{
	GetAck() ;
	return GetWord() ;
}

WORD WaitForAck(void)
{
    int saveTimeout = TimeLimit4D;
    void *saveCB = Callback4D;

    // check once per minute
    Callback4D = NULL;
    TimeLimit4D = 60 * 1000;
    do
    {
        GetAck();
    } while (Error4D != Err4D_OK);

    // Restore callback/timeout saves
    TimeLimit4D = saveTimeout;
    Callback4D = saveCB;

    return GetWord();
}
WORD GetAckRes2Words(WORD * word1, WORD * word2)
{
	int Result ;
	GetAck() ;
	Result = GetWord() ;
	*word1 = GetWord() ;
	*word2 = GetWord() ;
	return Result ;
}

void GetAck2Words(WORD * word1, WORD * word2)
{
	GetAck() ;
	*word1 = GetWord() ;
	*word2 = GetWord() ;
}

WORD GetAckResSector(t4DSector Sector)
{
	int Result;
	GetAck() ;
	Result = GetWord() ;
	getbytes(Sector, 512) ;
	return Result ;
}

WORD GetAckResStr(unsigned char * OutStr)
{
	int Result ;
	GetAck() ;
	Result = GetWord() ;
	getString(OutStr, Result) ;
	return Result ;
}

WORD GetAckResData(t4DByteArray OutData, WORD size)
{
	int Result ;
	GetAck() ;
	Result = GetWord() ;
	getbytes(OutData, size) ;
	return Result ;
}

/*
void SetBaudrate(int Newrate)
{
    struct termios serial_opts;
    WORD    nBaud;

    if (cPort < 0)
        return;

    // This is the only map from 4D Systems to Linux we support (for now)
    switch (Newrate)
    {
    case     BAUD_110:       nBaud =    B110 ; break ;
    case     BAUD_300:       nBaud =    B300 ; break ;
    case     BAUD_600:       nBaud =    B600 ; break ;
    case    BAUD_1200:       nBaud =   B1200 ; break ;
    case    BAUD_2400:       nBaud =   B2400 ; break ;
    case    BAUD_9600:       nBaud =   B9600 ; break ;
    case   BAUD_19200:       nBaud =  B19200 ; break ;
    case   BAUD_38400:       nBaud =  B38400 ; break ;
    case   BAUD_57600:       nBaud =  B57600 ; break ;
    case  BAUD_115200:       nBaud = B115200 ; break ;

    default:
      nBaud = B9600 ;
    }

    // Current config
    tcgetattr(cPort, &serial_opts);

    cfmakeraw(&serial_opts);
    cfsetospeed(&serial_opts, nBaud);
    cfsetispeed(&serial_opts, nBaud);

    // set new config
    tcsetattr(cPort, TCSANOW, &serial_opts);

    return;
}

void SetThisBaudrate(int Newrate)
{
    if (cPort < 0)
        return;

    tcdrain(cPort);

    SetBaudrate(Newrate) ;

    usleep(1000) ;          // Display sleeps for 100

    return;
}
*/

/*
 * End Of Intrinsic 4DRoutines here
*/

/*
 * Starts of 4D Compound Routines
*/



void blitComtoDisplay(WORD  X, WORD  Y, WORD  Width, WORD  Height, t4DByteArray  Pixels)
{
  unsigned char  towrite[10] ;
  towrite[0]= F_blitComtoDisplay >> 8 ;
  towrite[1]= F_blitComtoDisplay ;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  towrite[6]= Width >> 8 ;
  towrite[7]= Width ;
  towrite[8]= Height >> 8 ;
  towrite[9]= Height ;
  WriteBytes(towrite, 10) ;
  WriteBytes(Pixels, Width*Height*2) ;
  GetAck() ;
}

WORD bus_Read8()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_bus_Read8 >> 8 ;
  towrite[1]= F_bus_Read8 ;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

void bus_Write8(WORD  Bits)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_bus_Write8 >> 8 ;
  towrite[1]= F_bus_Write8 ;
  towrite[2]= Bits >> 8 ;
  towrite[3]= Bits ;
  WriteBytes(towrite, 4) ;
  GetAck() ;
}

WORD charheight(unsigned char  TestChar)
{
  unsigned char  towrite[3] ;
  towrite[0]= F_charheight >> 8 ;
  towrite[1]= F_charheight ;
  towrite[2]= TestChar;
  WriteBytes(towrite, 3) ;
  return GetAckResp() ;
}

WORD charwidth(unsigned char  TestChar)
{
  unsigned char  towrite[3] ;
  towrite[0]= F_charwidth >> 8 ;
  towrite[1]= F_charwidth ;
  towrite[2]= TestChar;
  WriteBytes(towrite, 3) ;
  return GetAckResp() ;
}

WORD file_CallFunction(WORD  Handle, WORD  ArgCount, t4DWordArray  Args)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_file_CallFunction >> 8 ;
  towrite[1]= F_file_CallFunction ;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= ArgCount >> 8 ;
  towrite[5]= ArgCount ;
  WriteBytes(towrite, 6) ;
  WriteWords(Args, ArgCount) ;
  return GetAckResp() ;
}

WORD file_Close(WORD  Handle)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_file_Close >> 8 ;
  towrite[1]= F_file_Close & 0xFF ;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD file_Count(unsigned char *  Filename)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_Count >> 8 ;
  towrite[1]= F_file_Count ;
  WriteBytes(towrite, 2) ;
  WriteChars(Filename) ;
  return GetAckResp() ;
}

WORD file_Dir(unsigned char *  Filename)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_Dir >> 8 ;
  towrite[1]= F_file_Dir ;
  WriteBytes(towrite, 2) ;
  WriteChars(Filename) ;
  return GetAckResp() ;
}

WORD file_Erase(unsigned char *  Filename)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_Erase >> 8 ;
  towrite[1]= F_file_Erase ;
  WriteBytes(towrite, 2) ;
  WriteChars(Filename) ;
  return GetAckResp() ;
}

WORD file_Error()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_Error >> 8 ;
  towrite[1]= F_file_Error & 0xFF;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

WORD file_Exec(unsigned char *  Filename, WORD  ArgCount, t4DWordArray  Args)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_Exec >> 8 ;
  towrite[1]= F_file_Exec ;
  WriteBytes(towrite, 2) ;
  WriteChars(Filename) ;
  towrite[0]= ArgCount >> 8 ;
  towrite[1]= ArgCount ;
  WriteBytes(towrite, 2) ;
  WriteWords(Args, ArgCount) ;
  return GetAckResp() ;
}

WORD file_Exists(unsigned char *  Filename)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_Exists >> 8 ;
  towrite[1]= F_file_Exists ;
  WriteBytes(towrite, 2) ;
  WriteChars(Filename) ;
  return GetAckResp() ;
}

WORD file_FindFirst(unsigned char *  Filename)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_FindFirst >> 8 ;
  towrite[1]= F_file_FindFirst ;
  WriteBytes(towrite, 2) ;
  WriteChars(Filename) ;
  return GetAckResp() ;
}

WORD file_FindFirstRet(unsigned char *  Filename, unsigned char *  StringIn)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_FindFirstRet >> 8 ;
  towrite[1]= F_file_FindFirstRet ;
  WriteBytes(towrite, 2) ;
  WriteChars(Filename) ;
  return GetAckResStr(StringIn) ;
}

WORD file_FindNext()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_FindNext >> 8 ;
  towrite[1]= F_file_FindNext & 0xFF;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

WORD file_FindNextRet(unsigned char *  StringIn)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_FindNextRet >> 8 ;
  towrite[1]= F_file_FindNextRet ;
  WriteBytes(towrite, 2) ;
  return GetAckResStr(StringIn) ;
}

unsigned char file_GetC(WORD  Handle)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_file_GetC >> 8 ;
  towrite[1]= F_file_GetC & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD file_GetS(unsigned char *  StringIn, WORD  Size, WORD  Handle)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_file_GetS >> 8 ;
  towrite[1]= F_file_GetS ;
  towrite[2]= Size >> 8 ;
  towrite[3]= Size ;
  towrite[4]= Handle >> 8 ;
  towrite[5]= Handle ;
  WriteBytes(towrite, 6) ;
  return GetAckResStr(StringIn) ;
}

WORD file_GetW(WORD  Handle)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_file_GetW >> 8 ;
  towrite[1]= F_file_GetW & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD file_Image(WORD  X, WORD  Y, WORD  Handle)
{
  unsigned char  towrite[8] ;
  towrite[0]= F_file_Image >> 8 ;
  towrite[1]= F_file_Image & 0xFF;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  towrite[6]= Handle >> 8 ;
  towrite[7]= Handle ;
  WriteBytes(towrite, 8) ;
  return GetAckResp() ;
}

WORD file_Index(WORD  Handle, WORD  HiSize, WORD  LoSize, WORD  Recordnum)
{
  unsigned char  towrite[10] ;
  towrite[0]= F_file_Index >> 8 ;
  towrite[1]= F_file_Index & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= HiSize >> 8 ;
  towrite[5]= HiSize ;
  towrite[6]= LoSize >> 8 ;
  towrite[7]= LoSize ;
  towrite[8]= Recordnum >> 8 ;
  towrite[9]= Recordnum ;
  WriteBytes(towrite, 10) ;
  return GetAckResp() ;
}

WORD file_LoadFunction(unsigned char *  Filename)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_LoadFunction >> 8 ;
  towrite[1]= F_file_LoadFunction ;
  WriteBytes(towrite, 2) ;
  WriteChars(Filename) ;
  return GetAckResp() ;
}

WORD file_LoadImageControl(unsigned char *  Datname, unsigned char *  GCIName, WORD  Mode)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_LoadImageControl >> 8 ;
  towrite[1]= F_file_LoadImageControl ;
  WriteBytes(towrite, 2) ;
  WriteChars(Datname) ;
  WriteChars(GCIName) ;
  towrite[0]= Mode >> 8 ;
  towrite[1]= Mode ;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

WORD file_Mount()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_Mount >> 8 ;
  towrite[1]= F_file_Mount & 0xFF;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

WORD file_Open(unsigned char *  Filename, unsigned char  Mode)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_Open >> 8 ;
  towrite[1]= F_file_Open ;
  WriteBytes(towrite, 2) ;
  WriteChars(Filename) ;
  towrite[0]= Mode;
  WriteBytes(towrite, 1) ;
  return GetAckResp() ;
}

WORD file_PlayWAV(unsigned char *  Filename)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_PlayWAV >> 8 ;
  towrite[1]= F_file_PlayWAV ;
  WriteBytes(towrite, 2) ;
  WriteChars(Filename) ;
  return GetAckResp() ;
}

WORD file_PutC(unsigned char  Character, WORD  Handle)
{
  unsigned char  towrite[5] ;
  towrite[0]= F_file_PutC >> 8 ;
  towrite[1]= F_file_PutC ;
  towrite[2]= Character;
  towrite[3]= Handle >> 8 ;
  towrite[4]= Handle ;
  WriteBytes(towrite, 5) ;
  return GetAckResp() ;
}

WORD file_PutS(unsigned char *  StringOut, WORD  Handle)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_PutS >> 8 ;
  towrite[1]= F_file_PutS ;
  WriteBytes(towrite, 2) ;
  WriteChars(StringOut) ;
  towrite[0]= Handle >> 8 ;
  towrite[1]= Handle ;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

WORD file_PutW(WORD  Word, WORD  Handle)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_file_PutW >> 8 ;
  towrite[1]= F_file_PutW & 0xFF;
  towrite[2]= Word >> 8 ;
  towrite[3]= Word ;
  towrite[4]= Handle >> 8 ;
  towrite[5]= Handle ;
  WriteBytes(towrite, 6) ;
  return GetAckResp() ;
}

WORD file_Read(t4DByteArray  Data, WORD  Size, WORD  Handle)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_file_Read >> 8 ;
  towrite[1]= F_file_Read ;
  towrite[2]= Size >> 8 ;
  towrite[3]= Size ;
  towrite[4]= Handle >> 8 ;
  towrite[5]= Handle ;
  WriteBytes(towrite, 6) ;
  return GetAckResData(Data,Size) ;
}

WORD file_Rewind(WORD  Handle)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_file_Rewind >> 8 ;
  towrite[1]= F_file_Rewind & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD file_Run(unsigned char *  Filename, WORD  ArgCount, t4DWordArray  Args)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_Run >> 8 ;
  towrite[1]= F_file_Run ;
  WriteBytes(towrite, 2) ;
  WriteChars(Filename) ;
  towrite[0]= ArgCount >> 8 ;
  towrite[1]= ArgCount ;
  WriteBytes(towrite, 2) ;
  WriteWords(Args, ArgCount) ;
  return GetAckResp() ;
}

WORD file_ScreenCapture(WORD  X, WORD  Y, WORD  Width, WORD  Height, WORD  Handle)
{
  unsigned char  towrite[12] ;
  towrite[0]= F_file_ScreenCapture >> 8 ;
  towrite[1]= F_file_ScreenCapture & 0xFF;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  towrite[6]= Width >> 8 ;
  towrite[7]= Width ;
  towrite[8]= Height >> 8 ;
  towrite[9]= Height ;
  towrite[10]= Handle >> 8 ;
  towrite[11]= Handle ;
  WriteBytes(towrite, 12) ;
  return GetAckResp() ;
}

WORD file_Seek(WORD  Handle, WORD  HiWord, WORD  LoWord)
{
  unsigned char  towrite[8] ;
  towrite[0]= F_file_Seek >> 8 ;
  towrite[1]= F_file_Seek & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= HiWord >> 8 ;
  towrite[5]= HiWord ;
  towrite[6]= LoWord >> 8 ;
  towrite[7]= LoWord ;
  WriteBytes(towrite, 8) ;
  return GetAckResp() ;
}

WORD file_Size(WORD  Handle, WORD *  HiWord, WORD *  LoWord)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_file_Size >> 8 ;
  towrite[1]= F_file_Size ;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  WriteBytes(towrite, 4) ;
  return GetAckRes2Words(HiWord,LoWord) ;
}

WORD file_Tell(WORD  Handle, WORD *  HiWord, WORD *  LoWord)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_file_Tell >> 8 ;
  towrite[1]= F_file_Tell ;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  WriteBytes(towrite, 4) ;
  return GetAckRes2Words(HiWord,LoWord) ;
}

void file_Unmount()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_file_Unmount >> 8 ;
  towrite[1]= F_file_Unmount & 0xFF;
  WriteBytes(towrite, 2) ;
  GetAck() ;
}

WORD file_Write(WORD  Size, t4DByteArray  Source, WORD  Handle)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_file_Write >> 8 ;
  towrite[1]= F_file_Write ;
  towrite[2]= Size >> 8 ;
  towrite[3]= Size ;
  WriteBytes(towrite, 4) ;
  WriteBytes(Source, Size) ;
  towrite[0]= Handle >> 8 ;
  towrite[1]= Handle ;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

WORD gfx_BevelShadow(WORD  Value)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_BevelShadow >> 8 ;
  towrite[1]= F_gfx_BevelShadow & 0xFF;
  towrite[2]= Value >> 8 ;
  towrite[3]= Value ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD gfx_BevelWidth(WORD  Value)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_BevelWidth >> 8 ;
  towrite[1]= F_gfx_BevelWidth & 0xFF;
  towrite[2]= Value >> 8 ;
  towrite[3]= Value ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD gfx_BGcolour(WORD  Color)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_BGcolour >> 8 ;
  towrite[1]= F_gfx_BGcolour & 0xFF;
  towrite[2]= Color >> 8 ;
  towrite[3]= Color ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

void gfx_Button(WORD  Up, WORD  x, WORD  y, WORD  buttonColour, WORD  txtColour, WORD  font, WORD  txtWidth, WORD  txtHeight, unsigned char *   text)
{
  unsigned char  towrite[18] ;
  towrite[0]= F_gfx_Button >> 8 ;
  towrite[1]= F_gfx_Button ;
  towrite[2]= Up >> 8 ;
  towrite[3]= Up ;
  towrite[4]= x >> 8 ;
  towrite[5]= x ;
  towrite[6]= y >> 8 ;
  towrite[7]= y ;
  towrite[8]= buttonColour >> 8 ;
  towrite[9]= buttonColour ;
  towrite[10]= txtColour >> 8 ;
  towrite[11]= txtColour ;
  towrite[12]= font >> 8 ;
  towrite[13]= font ;
  towrite[14]= txtWidth >> 8 ;
  towrite[15]= txtWidth ;
  towrite[16]= txtHeight >> 8 ;
  towrite[17]= txtHeight ;
  WriteBytes(towrite, 18) ;
  WriteChars( text) ;
  GetAck() ;
}

void gfx_ChangeColour(WORD  OldColor, WORD  NewColor)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_gfx_ChangeColour >> 8 ;
  towrite[1]= F_gfx_ChangeColour & 0xFF;
  towrite[2]= OldColor >> 8 ;
  towrite[3]= OldColor ;
  towrite[4]= NewColor >> 8 ;
  towrite[5]= NewColor ;
  WriteBytes(towrite, 6) ;
  GetAck() ;
}

void gfx_Circle(WORD  X, WORD  Y, WORD  Radius, WORD  Color)
{
  unsigned char  towrite[10] ;
  towrite[0]= F_gfx_Circle >> 8 ;
  towrite[1]= F_gfx_Circle & 0xFF;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  towrite[6]= Radius >> 8 ;
  towrite[7]= Radius ;
  towrite[8]= Color >> 8 ;
  towrite[9]= Color ;
  WriteBytes(towrite, 10) ;
  GetAck() ;
}

void gfx_CircleFilled(WORD  X, WORD  Y, WORD  Radius, WORD  Color)
{
  unsigned char  towrite[10] ;
  towrite[0]= F_gfx_CircleFilled >> 8 ;
  towrite[1]= F_gfx_CircleFilled & 0xFF;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  towrite[6]= Radius >> 8 ;
  towrite[7]= Radius ;
  towrite[8]= Color >> 8 ;
  towrite[9]= Color ;
  WriteBytes(towrite, 10) ;
  GetAck() ;
}

void gfx_Clipping(WORD  OnOff)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_Clipping >> 8 ;
  towrite[1]= F_gfx_Clipping & 0xFF;
  towrite[2]= OnOff >> 8 ;
  towrite[3]= OnOff ;
  WriteBytes(towrite, 4) ;
  GetAck() ;
}

void gfx_ClipWindow(WORD  X1, WORD  Y1, WORD  X2, WORD  Y2)
{
  unsigned char  towrite[10] ;
  towrite[0]= F_gfx_ClipWindow >> 8 ;
  towrite[1]= F_gfx_ClipWindow & 0xFF;
  towrite[2]= X1 >> 8 ;
  towrite[3]= X1 ;
  towrite[4]= Y1 >> 8 ;
  towrite[5]= Y1 ;
  towrite[6]= X2 >> 8 ;
  towrite[7]= X2 ;
  towrite[8]= Y2 >> 8 ;
  towrite[9]= Y2 ;
  WriteBytes(towrite, 10) ;
  GetAck() ;
}

void gfx_Cls()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_gfx_Cls >> 8 ;
  towrite[1]= F_gfx_Cls ;
  WriteBytes(towrite, 2) ;
  GetAck() ;
}

WORD gfx_Contrast(WORD  Contrast)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_Contrast >> 8 ;
  towrite[1]= F_gfx_Contrast & 0xFF;
  towrite[2]= Contrast >> 8 ;
  towrite[3]= Contrast ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

void gfx_Ellipse(WORD  X, WORD  Y, WORD  Xrad, WORD  Yrad, WORD  Color)
{
  unsigned char  towrite[12] ;
  towrite[0]= F_gfx_Ellipse >> 8 ;
  towrite[1]= F_gfx_Ellipse & 0xFF;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  towrite[6]= Xrad >> 8 ;
  towrite[7]= Xrad ;
  towrite[8]= Yrad >> 8 ;
  towrite[9]= Yrad ;
  towrite[10]= Color >> 8 ;
  towrite[11]= Color ;
  WriteBytes(towrite, 12) ;
  GetAck() ;
}

void gfx_EllipseFilled(WORD  X, WORD  Y, WORD  Xrad, WORD  Yrad, WORD  Color)
{
  unsigned char  towrite[12] ;
  towrite[0]= F_gfx_EllipseFilled >> 8 ;
  towrite[1]= F_gfx_EllipseFilled & 0xFF;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  towrite[6]= Xrad >> 8 ;
  towrite[7]= Xrad ;
  towrite[8]= Yrad >> 8 ;
  towrite[9]= Yrad ;
  towrite[10]= Color >> 8 ;
  towrite[11]= Color ;
  WriteBytes(towrite, 12) ;
  GetAck() ;
}

WORD gfx_FrameDelay(WORD  Msec)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_FrameDelay >> 8 ;
  towrite[1]= F_gfx_FrameDelay & 0xFF;
  towrite[2]= Msec >> 8 ;
  towrite[3]= Msec ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD gfx_Get(WORD  Mode)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_Get >> 8 ;
  towrite[1]= F_gfx_Get & 0xFF;
  towrite[2]= Mode >> 8 ;
  towrite[3]= Mode ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD gfx_GetPixel(WORD  X, WORD  Y)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_gfx_GetPixel >> 8 ;
  towrite[1]= F_gfx_GetPixel & 0xFF;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  WriteBytes(towrite, 6) ;
  return GetAckResp() ;
}

void gfx_Line(WORD  X1, WORD  Y1, WORD  X2, WORD  Y2, WORD  Color)
{
  unsigned char  towrite[12] ;
  towrite[0]= F_gfx_Line >> 8 ;
  towrite[1]= F_gfx_Line & 0xFF;
  towrite[2]= X1 >> 8 ;
  towrite[3]= X1 ;
  towrite[4]= Y1 >> 8 ;
  towrite[5]= Y1 ;
  towrite[6]= X2 >> 8 ;
  towrite[7]= X2 ;
  towrite[8]= Y2 >> 8 ;
  towrite[9]= Y2 ;
  towrite[10]= Color >> 8 ;
  towrite[11]= Color ;
  WriteBytes(towrite, 12) ;
  GetAck() ;
}

WORD gfx_LinePattern(WORD  Pattern)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_LinePattern >> 8 ;
  towrite[1]= F_gfx_LinePattern & 0xFF;
  towrite[2]= Pattern >> 8 ;
  towrite[3]= Pattern ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

void gfx_LineTo(WORD  X, WORD  Y)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_gfx_LineTo >> 8 ;
  towrite[1]= F_gfx_LineTo & 0xFF;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  WriteBytes(towrite, 6) ;
  GetAck() ;
}

void gfx_MoveTo(WORD  X, WORD  Y)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_gfx_MoveTo >> 8 ;
  towrite[1]= F_gfx_MoveTo ;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  WriteBytes(towrite, 6) ;
  GetAck() ;
}

WORD gfx_Orbit(WORD  Angle, WORD  Distance, WORD *  Xdest, WORD *  Ydest)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_gfx_Orbit >> 8 ;
  towrite[1]= F_gfx_Orbit ;
  towrite[2]= Angle >> 8 ;
  towrite[3]= Angle ;
  towrite[4]= Distance >> 8 ;
  towrite[5]= Distance ;
  WriteBytes(towrite, 6) ;
  GetAck2Words(Xdest,Ydest) ;
  return 0 ;
}

WORD gfx_OutlineColour(WORD  Color)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_OutlineColour >> 8 ;
  towrite[1]= F_gfx_OutlineColour & 0xFF;
  towrite[2]= Color >> 8 ;
  towrite[3]= Color ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

void gfx_Panel(WORD  Raised, WORD  X, WORD  Y, WORD  Width, WORD  Height, WORD  Color)
{
  unsigned char  towrite[14] ;
  towrite[0]= F_gfx_Panel >> 8 ;
  towrite[1]= F_gfx_Panel & 0xFF;
  towrite[2]= Raised >> 8 ;
  towrite[3]= Raised ;
  towrite[4]= X >> 8 ;
  towrite[5]= X ;
  towrite[6]= Y >> 8 ;
  towrite[7]= Y ;
  towrite[8]= Width >> 8 ;
  towrite[9]= Width ;
  towrite[10]= Height >> 8 ;
  towrite[11]= Height ;
  towrite[12]= Color >> 8 ;
  towrite[13]= Color ;
  WriteBytes(towrite, 14) ;
  GetAck() ;
}

void gfx_Polygon(WORD  n, t4DWordArray  Xvalues, t4DWordArray  Yvalues, WORD  Color)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_Polygon >> 8 ;
  towrite[1]= F_gfx_Polygon ;
  towrite[2]= n >> 8 ;
  towrite[3]= n ;
  WriteBytes(towrite, 4) ;
  WriteWords(Xvalues, n) ;
  WriteWords(Yvalues, n) ;
  towrite[0]= Color >> 8 ;
  towrite[1]= Color ;
  WriteBytes(towrite, 2) ;
  GetAck() ;
}

void gfx_PolygonFilled(WORD  n, t4DWordArray  Xvalues, t4DWordArray  Yvalues, WORD  Color)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_PolygonFilled >> 8 ;
  towrite[1]= F_gfx_PolygonFilled ;
  towrite[2]= n >> 8 ;
  towrite[3]= n ;
  WriteBytes(towrite, 4) ;
  WriteWords(Xvalues, n) ;
  WriteWords(Yvalues, n) ;
  towrite[0]= Color >> 8 ;
  towrite[1]= Color ;
  WriteBytes(towrite, 2) ;
  GetAck() ;
}

void gfx_Polyline(WORD  n, t4DWordArray  Xvalues, t4DWordArray  Yvalues, WORD  Color)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_Polyline >> 8 ;
  towrite[1]= F_gfx_Polyline ;
  towrite[2]= n >> 8 ;
  towrite[3]= n ;
  WriteBytes(towrite, 4) ;
  WriteWords(Xvalues, n) ;
  WriteWords(Yvalues, n) ;
  towrite[0]= Color >> 8 ;
  towrite[1]= Color ;
  WriteBytes(towrite, 2) ;
  GetAck() ;
}

void gfx_PutPixel(WORD  X, WORD  Y, WORD  Color)
{
  unsigned char  towrite[8] ;
  towrite[0]= F_gfx_PutPixel >> 8 ;
  towrite[1]= F_gfx_PutPixel & 0xFF;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  towrite[6]= Color >> 8 ;
  towrite[7]= Color ;
  WriteBytes(towrite, 8) ;
  GetAck() ;
}

void gfx_Rectangle(WORD  X1, WORD  Y1, WORD  X2, WORD  Y2, WORD  Color)
{
  unsigned char  towrite[12] ;
  towrite[0]= F_gfx_Rectangle >> 8 ;
  towrite[1]= F_gfx_Rectangle & 0xFF;
  towrite[2]= X1 >> 8 ;
  towrite[3]= X1 ;
  towrite[4]= Y1 >> 8 ;
  towrite[5]= Y1 ;
  towrite[6]= X2 >> 8 ;
  towrite[7]= X2 ;
  towrite[8]= Y2 >> 8 ;
  towrite[9]= Y2 ;
  towrite[10]= Color >> 8 ;
  towrite[11]= Color ;
  WriteBytes(towrite, 12) ;
  GetAck() ;
}

void gfx_RectangleFilled(WORD  X1, WORD  Y1, WORD  X2, WORD  Y2, WORD  Color)
{
  unsigned char  towrite[12] ;
  towrite[0]= F_gfx_RectangleFilled >> 8 ;
  towrite[1]= F_gfx_RectangleFilled & 0xFF;
  towrite[2]= X1 >> 8 ;
  towrite[3]= X1 ;
  towrite[4]= Y1 >> 8 ;
  towrite[5]= Y1 ;
  towrite[6]= X2 >> 8 ;
  towrite[7]= X2 ;
  towrite[8]= Y2 >> 8 ;
  towrite[9]= Y2 ;
  towrite[10]= Color >> 8 ;
  towrite[11]= Color ;
  WriteBytes(towrite, 12) ;
  GetAck() ;
}

void gfx_ScreenCopyPaste(WORD  Xs, WORD  Ys, WORD  Xd, WORD  Yd, WORD  Width, WORD  Height)
{
  unsigned char  towrite[14] ;
  towrite[0]= F_gfx_ScreenCopyPaste >> 8 ;
  towrite[1]= F_gfx_ScreenCopyPaste & 0xFF;
  towrite[2]= Xs >> 8 ;
  towrite[3]= Xs ;
  towrite[4]= Ys >> 8 ;
  towrite[5]= Ys ;
  towrite[6]= Xd >> 8 ;
  towrite[7]= Xd ;
  towrite[8]= Yd >> 8 ;
  towrite[9]= Yd ;
  towrite[10]= Width >> 8 ;
  towrite[11]= Width ;
  towrite[12]= Height >> 8 ;
  towrite[13]= Height ;
  WriteBytes(towrite, 14) ;
  GetAck() ;
}

WORD gfx_ScreenMode(WORD  ScreenMode)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_ScreenMode >> 8 ;
  towrite[1]= F_gfx_ScreenMode & 0xFF;
  towrite[2]= ScreenMode >> 8 ;
  towrite[3]= ScreenMode ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

void gfx_Set(WORD  Func, WORD  Value)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_gfx_Set >> 8 ;
  towrite[1]= F_gfx_Set ;
  towrite[2]= Func >> 8 ;
  towrite[3]= Func ;
  towrite[4]= Value >> 8 ;
  towrite[5]= Value ;
  WriteBytes(towrite, 6) ;
  GetAck() ;
}

void gfx_SetClipRegion()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_gfx_SetClipRegion >> 8 ;
  towrite[1]= F_gfx_SetClipRegion & 0xFF;
  WriteBytes(towrite, 2) ;
  GetAck() ;
}

WORD gfx_Slider(WORD  Mode, WORD  X1, WORD  Y1, WORD  X2, WORD  Y2, WORD  Color, WORD  Scale, WORD  Value)
{
  unsigned char  towrite[18] ;
  towrite[0]= F_gfx_Slider >> 8 ;
  towrite[1]= F_gfx_Slider & 0xFF;
  towrite[2]= Mode >> 8 ;
  towrite[3]= Mode ;
  towrite[4]= X1 >> 8 ;
  towrite[5]= X1 ;
  towrite[6]= Y1 >> 8 ;
  towrite[7]= Y1 ;
  towrite[8]= X2 >> 8 ;
  towrite[9]= X2 ;
  towrite[10]= Y2 >> 8 ;
  towrite[11]= Y2 ;
  towrite[12]= Color >> 8 ;
  towrite[13]= Color ;
  towrite[14]= Scale >> 8 ;
  towrite[15]= Scale ;
  towrite[16]= Value >> 8 ;
  towrite[17]= Value ;
  WriteBytes(towrite, 18) ;
  return GetAckResp() ;
}

WORD gfx_Transparency(WORD  OnOff)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_Transparency >> 8 ;
  towrite[1]= F_gfx_Transparency & 0xFF;
  towrite[2]= OnOff >> 8 ;
  towrite[3]= OnOff ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD gfx_TransparentColour(WORD  Color)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_gfx_TransparentColour >> 8 ;
  towrite[1]= F_gfx_TransparentColour & 0xFF;
  towrite[2]= Color >> 8 ;
  towrite[3]= Color ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

void gfx_Triangle(WORD  X1, WORD  Y1, WORD  X2, WORD  Y2, WORD  X3, WORD  Y3, WORD  Color)
{
  unsigned char  towrite[16] ;
  towrite[0]= F_gfx_Triangle >> 8 ;
  towrite[1]= F_gfx_Triangle & 0xFF;
  towrite[2]= X1 >> 8 ;
  towrite[3]= X1 ;
  towrite[4]= Y1 >> 8 ;
  towrite[5]= Y1 ;
  towrite[6]= X2 >> 8 ;
  towrite[7]= X2 ;
  towrite[8]= Y2 >> 8 ;
  towrite[9]= Y2 ;
  towrite[10]= X3 >> 8 ;
  towrite[11]= X3 ;
  towrite[12]= Y3 >> 8 ;
  towrite[13]= Y3 ;
  towrite[14]= Color >> 8 ;
  towrite[15]= Color ;
  WriteBytes(towrite, 16) ;
  GetAck() ;
}

void gfx_TriangleFilled(WORD  X1, WORD  Y1, WORD  X2, WORD  Y2, WORD  X3, WORD  Y3, WORD  Color)
{
  unsigned char  towrite[16] ;
  towrite[0]= F_gfx_TriangleFilled >> 8 ;
  towrite[1]= F_gfx_TriangleFilled & 0xFF;
  towrite[2]= X1 >> 8 ;
  towrite[3]= X1 ;
  towrite[4]= Y1 >> 8 ;
  towrite[5]= Y1 ;
  towrite[6]= X2 >> 8 ;
  towrite[7]= X2 ;
  towrite[8]= Y2 >> 8 ;
  towrite[9]= Y2 ;
  towrite[10]= X3 >> 8 ;
  towrite[11]= X3 ;
  towrite[12]= Y3 >> 8 ;
  towrite[13]= Y3 ;
  towrite[14]= Color >> 8 ;
  towrite[15]= Color ;
  WriteBytes(towrite, 16) ;
  GetAck() ;
}

WORD img_ClearAttributes(WORD  Handle, WORD  Index, WORD  Value)
{
  unsigned char  towrite[8] ;
  towrite[0]= F_img_ClearAttributes >> 8 ;
  towrite[1]= F_img_ClearAttributes & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= Index >> 8 ;
  towrite[5]= Index ;
  towrite[6]= Value >> 8 ;
  towrite[7]= Value ;
  WriteBytes(towrite, 8) ;
  return GetAckResp() ;
}

WORD img_Darken(WORD  Handle, WORD  Index)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_img_Darken >> 8 ;
  towrite[1]= F_img_Darken & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= Index >> 8 ;
  towrite[5]= Index ;
  WriteBytes(towrite, 6) ;
  return GetAckResp() ;
}

WORD img_Disable(WORD  Handle, WORD  Index)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_img_Disable >> 8 ;
  towrite[1]= F_img_Disable & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= Index >> 8 ;
  towrite[5]= Index ;
  WriteBytes(towrite, 6) ;
  return GetAckResp() ;
}

WORD img_Enable(WORD  Handle, WORD  Index)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_img_Enable >> 8 ;
  towrite[1]= F_img_Enable & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= Index >> 8 ;
  towrite[5]= Index ;
  WriteBytes(towrite, 6) ;
  return GetAckResp() ;
}

WORD img_GetWord(WORD  Handle, WORD  Index, WORD  Offset )
{
  unsigned char  towrite[8] ;
  towrite[0]= F_img_GetWord >> 8 ;
  towrite[1]= F_img_GetWord & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= Index >> 8 ;
  towrite[5]= Index ;
  towrite[6]= Offset  >> 8 ;
  towrite[7]= Offset  ;
  WriteBytes(towrite, 8) ;
  return GetAckResp() ;
}

WORD img_Lighten(WORD  Handle, WORD  Index)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_img_Lighten >> 8 ;
  towrite[1]= F_img_Lighten & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= Index >> 8 ;
  towrite[5]= Index ;
  WriteBytes(towrite, 6) ;
  return GetAckResp() ;
}

WORD img_SetAttributes(WORD  Handle, WORD  Index, WORD  Value)
{
  unsigned char  towrite[8] ;
  towrite[0]= F_img_SetAttributes >> 8 ;
  towrite[1]= F_img_SetAttributes & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= Index >> 8 ;
  towrite[5]= Index ;
  towrite[6]= Value >> 8 ;
  towrite[7]= Value ;
  WriteBytes(towrite, 8) ;
  return GetAckResp() ;
}

WORD img_SetPosition(WORD  Handle, WORD  Index, WORD  Xpos, WORD  Ypos)
{
  unsigned char  towrite[10] ;
  towrite[0]= F_img_SetPosition >> 8 ;
  towrite[1]= F_img_SetPosition & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= Index >> 8 ;
  towrite[5]= Index ;
  towrite[6]= Xpos >> 8 ;
  towrite[7]= Xpos ;
  towrite[8]= Ypos >> 8 ;
  towrite[9]= Ypos ;
  WriteBytes(towrite, 10) ;
  return GetAckResp() ;
}

WORD img_SetWord(WORD  Handle, WORD  Index, WORD  Offset , WORD  Word)
{
  unsigned char  towrite[10] ;
  towrite[0]= F_img_SetWord >> 8 ;
  towrite[1]= F_img_SetWord & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= Index >> 8 ;
  towrite[5]= Index ;
  towrite[6]= Offset  >> 8 ;
  towrite[7]= Offset  ;
  towrite[8]= Word >> 8 ;
  towrite[9]= Word ;
  WriteBytes(towrite, 10) ;
  return GetAckResp() ;
}

WORD img_Show(WORD  Handle, WORD  Index)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_img_Show >> 8 ;
  towrite[1]= F_img_Show & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= Index >> 8 ;
  towrite[5]= Index ;
  WriteBytes(towrite, 6) ;
  return GetAckResp() ;
}

WORD img_Touched(WORD  Handle, WORD  Index)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_img_Touched >> 8 ;
  towrite[1]= F_img_Touched & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  towrite[4]= Index >> 8 ;
  towrite[5]= Index ;
  WriteBytes(towrite, 6) ;
  return GetAckResp() ;
}

WORD media_Flush()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_media_Flush >> 8 ;
  towrite[1]= F_media_Flush & 0xFF;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

void media_Image(WORD  X, WORD  Y)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_media_Image >> 8 ;
  towrite[1]= F_media_Image & 0xFF;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  WriteBytes(towrite, 6) ;
  GetAck() ;
}

WORD media_Init()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_media_Init >> 8 ;
  towrite[1]= F_media_Init & 0xFF;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

WORD media_RdSector(t4DSector  SectorIn)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_media_RdSector >> 8 ;
  towrite[1]= F_media_RdSector ;
  WriteBytes(towrite, 2) ;
  return GetAckResSector(SectorIn) ;
}

WORD media_ReadByte()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_media_ReadByte >> 8 ;
  towrite[1]= F_media_ReadByte & 0xFF;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

WORD media_ReadWord()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_media_ReadWord >> 8 ;
  towrite[1]= F_media_ReadWord & 0xFF;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

void media_SetAdd(WORD  HiWord, WORD  LoWord)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_media_SetAdd >> 8 ;
  towrite[1]= F_media_SetAdd & 0xFF;
  towrite[2]= HiWord >> 8 ;
  towrite[3]= HiWord ;
  towrite[4]= LoWord >> 8 ;
  towrite[5]= LoWord ;
  WriteBytes(towrite, 6) ;
  GetAck() ;
}

void media_SetSector(WORD  HiWord, WORD  LoWord)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_media_SetSector >> 8 ;
  towrite[1]= F_media_SetSector & 0xFF;
  towrite[2]= HiWord >> 8 ;
  towrite[3]= HiWord ;
  towrite[4]= LoWord >> 8 ;
  towrite[5]= LoWord ;
  WriteBytes(towrite, 6) ;
  GetAck() ;
}

void media_Video(WORD  X, WORD  Y)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_media_Video >> 8 ;
  towrite[1]= F_media_Video & 0xFF;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  WriteBytes(towrite, 6) ;
  GetAck() ;
}

void media_VideoFrame(WORD  X, WORD  Y, WORD  Framenumber)
{
  unsigned char  towrite[8] ;
  towrite[0]= F_media_VideoFrame >> 8 ;
  towrite[1]= F_media_VideoFrame & 0xFF;
  towrite[2]= X >> 8 ;
  towrite[3]= X ;
  towrite[4]= Y >> 8 ;
  towrite[5]= Y ;
  towrite[6]= Framenumber >> 8 ;
  towrite[7]= Framenumber ;
  WriteBytes(towrite, 8) ;
  GetAck() ;
}

WORD media_WriteByte(WORD  Byte)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_media_WriteByte >> 8 ;
  towrite[1]= F_media_WriteByte & 0xFF;
  towrite[2]= Byte >> 8 ;
  towrite[3]= Byte ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD media_WriteWord(WORD  Word)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_media_WriteWord >> 8 ;
  towrite[1]= F_media_WriteWord & 0xFF ;
  towrite[2]= Word >> 8 ;
  towrite[3]= Word ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD media_WrSector(t4DSector  SectorOut)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_media_WrSector >> 8 ;
  towrite[1]= F_media_WrSector ;
  WriteBytes(towrite, 2) ;
  WriteBytes(SectorOut, 512) ;
  return GetAckResp() ;
}

WORD mem_Free(WORD  Handle)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_mem_Free >> 8 ;
  towrite[1]= F_mem_Free & 0xFF;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD mem_Heap()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_mem_Heap >> 8 ;
  towrite[1]= F_mem_Heap & 0xFF;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

WORD peekM(WORD  Address)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_peekM >> 8 ;
  towrite[1]= F_peekM ;
  towrite[2]= Address >> 8 ;
  towrite[3]= Address ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD pin_HI(WORD  Pin)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_pin_HI >> 8 ;
  towrite[1]= F_pin_HI ;
  towrite[2]= Pin >> 8 ;
  towrite[3]= Pin ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD pin_LO(WORD  Pin)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_pin_LO >> 8 ;
  towrite[1]= F_pin_LO ;
  towrite[2]= Pin >> 8 ;
  towrite[3]= Pin ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD pin_Read(WORD  Pin)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_pin_Read >> 8 ;
  towrite[1]= F_pin_Read ;
  towrite[2]= Pin >> 8 ;
  towrite[3]= Pin ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD pin_Set(WORD  Mode, WORD  Pin)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_pin_Set >> 8 ;
  towrite[1]= F_pin_Set ;
  towrite[2]= Mode >> 8 ;
  towrite[3]= Mode ;
  towrite[4]= Pin >> 8 ;
  towrite[5]= Pin ;
  WriteBytes(towrite, 6) ;
  return GetAckResp() ;
}

void pokeM(WORD  Address, WORD  WordValue)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_pokeM >> 8 ;
  towrite[1]= F_pokeM ;
  towrite[2]= Address >> 8 ;
  towrite[3]= Address ;
  towrite[4]= WordValue >> 8 ;
  towrite[5]= WordValue ;
  WriteBytes(towrite, 6) ;
  GetAck() ;
}

void putCH(WORD  WordChar)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_putCH >> 8 ;
  towrite[1]= F_putCH ;
  towrite[2]= WordChar >> 8 ;
  towrite[3]= WordChar ;
  WriteBytes(towrite, 4) ;
  GetAck() ;
}

WORD putstr(unsigned char *  InString)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_putstr >> 8 ;
  towrite[1]= F_putstr ;
  WriteBytes(towrite, 2) ;
  WriteChars(InString) ;
  return GetAckResp() ;
}

WORD readString(WORD  Handle, unsigned char *  StringIn)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_readString >> 8 ;
  towrite[1]= F_readString ;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  WriteBytes(towrite, 4) ;
  return GetAckResStr(StringIn) ;
}

void setbaudWait(WORD  Newrate)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_setbaudWait >> 8 ;
  towrite[1]= F_setbaudWait ;
  towrite[2]= Newrate >> 8 ;
  towrite[3]= Newrate ;
  WriteBytes(towrite, 4) ;
  //SetThisBaudrate(Newrate) ; // change this systems baud rate to match new display rate, ACK is 100ms away
  GetAck() ;
}

void snd_BufSize(WORD  Bufsize)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_snd_BufSize >> 8 ;
  towrite[1]= F_snd_BufSize & 0xFF;
  towrite[2]= Bufsize >> 8 ;
  towrite[3]= Bufsize ;
  WriteBytes(towrite, 4) ;
  GetAck() ;
}

void snd_Continue()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_snd_Continue >> 8 ;
  towrite[1]= F_snd_Continue & 0xFF;
  WriteBytes(towrite, 2) ;
  GetAck() ;
}

void snd_Pause()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_snd_Pause >> 8 ;
  towrite[1]= F_snd_Pause & 0xFF;
  WriteBytes(towrite, 2) ;
  GetAck() ;
}

WORD snd_Pitch(WORD  Pitch)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_snd_Pitch >> 8 ;
  towrite[1]= F_snd_Pitch & 0xFF;
  towrite[2]= Pitch >> 8 ;
  towrite[3]= Pitch ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD snd_Playing()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_snd_Playing >> 8 ;
  towrite[1]= F_snd_Playing & 0xFF;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

void snd_Stop()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_snd_Stop >> 8 ;
  towrite[1]= F_snd_Stop & 0xFF;
  WriteBytes(towrite, 2) ;
  GetAck() ;
}

void snd_Volume(WORD  Volume)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_snd_Volume >> 8 ;
  towrite[1]= F_snd_Volume & 0xFF;
  towrite[2]= Volume >> 8 ;
  towrite[3]= Volume ;
  WriteBytes(towrite, 4) ;
  GetAck() ;
}

WORD sys_GetModel(unsigned char *  ModelStr)
{
  unsigned char  towrite[2] ;
  towrite[0]= F_sys_GetModel >> 8 ;
  towrite[1]= F_sys_GetModel ;
  WriteBytes(towrite, 2) ;
  return GetAckResStr(ModelStr) ;
}

WORD sys_GetPmmC()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_sys_GetPmmC >> 8 ;
  towrite[1]= F_sys_GetPmmC ;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

WORD sys_GetVersion()
{
  unsigned char  towrite[2] ;
  towrite[0]= F_sys_GetVersion >> 8 ;
  towrite[1]= F_sys_GetVersion ;
  WriteBytes(towrite, 2) ;
  return GetAckResp() ;
}

WORD sys_Sleep(WORD  Units)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_sys_Sleep >> 8 ;
  towrite[1]= F_sys_Sleep & 0xFF;
  towrite[2]= Units >> 8 ;
  towrite[3]= Units ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

void touch_DetectRegion(WORD  X1, WORD  Y1, WORD  X2, WORD  Y2)
{
  unsigned char  towrite[10] ;
  towrite[0]= F_touch_DetectRegion >> 8 ;
  towrite[1]= F_touch_DetectRegion & 0xFF;
  towrite[2]= X1 >> 8 ;
  towrite[3]= X1 ;
  towrite[4]= Y1 >> 8 ;
  towrite[5]= Y1 ;
  towrite[6]= X2 >> 8 ;
  towrite[7]= X2 ;
  towrite[8]= Y2 >> 8 ;
  towrite[9]= Y2 ;
  WriteBytes(towrite, 10) ;
  GetAck() ;
}

WORD touch_Get(WORD  Mode)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_touch_Get >> 8 ;
  towrite[1]= F_touch_Get & 0xFF;
  towrite[2]= Mode >> 8 ;
  towrite[3]= Mode ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

void touch_Set(WORD  Mode)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_touch_Set >> 8 ;
  towrite[1]= F_touch_Set & 0xFF;
  towrite[2]= Mode >> 8 ;
  towrite[3]= Mode ;
  WriteBytes(towrite, 4) ;
  GetAck() ;
}

WORD txt_Attributes(WORD  Attribs)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_Attributes >> 8 ;
  towrite[1]= F_txt_Attributes ;
  towrite[2]= Attribs >> 8 ;
  towrite[3]= Attribs ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD txt_BGcolour(WORD  Color)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_BGcolour >> 8 ;
  towrite[1]= F_txt_BGcolour ;
  towrite[2]= Color >> 8 ;
  towrite[3]= Color ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD txt_Bold(WORD  Bold)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_Bold >> 8 ;
  towrite[1]= F_txt_Bold ;
  towrite[2]= Bold >> 8 ;
  towrite[3]= Bold ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD txt_FGcolour(WORD  Color)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_FGcolour >> 8 ;
  towrite[1]= F_txt_FGcolour ;
  towrite[2]= Color >> 8 ;
  towrite[3]= Color ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD txt_FontID(WORD  FontNumber)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_FontID >> 8 ;
  towrite[1]= F_txt_FontID ;
  towrite[2]= FontNumber >> 8 ;
  towrite[3]= FontNumber ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD txt_Height(WORD  Multiplier)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_Height >> 8 ;
  towrite[1]= F_txt_Height ;
  towrite[2]= Multiplier >> 8 ;
  towrite[3]= Multiplier ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD txt_Inverse(WORD  Inverse)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_Inverse >> 8 ;
  towrite[1]= F_txt_Inverse ;
  towrite[2]= Inverse >> 8 ;
  towrite[3]= Inverse ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD txt_Italic(WORD  Italic)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_Italic >> 8 ;
  towrite[1]= F_txt_Italic ;
  towrite[2]= Italic >> 8 ;
  towrite[3]= Italic ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

void txt_MoveCursor(WORD  Line, WORD  Column)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_txt_MoveCursor >> 8 ;
  towrite[1]= F_txt_MoveCursor ;
  towrite[2]= Line >> 8 ;
  towrite[3]= Line ;
  towrite[4]= Column >> 8 ;
  towrite[5]= Column ;
  WriteBytes(towrite, 6) ;
  GetAck() ;
}

WORD txt_Opacity(WORD  TransparentOpaque)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_Opacity >> 8 ;
  towrite[1]= F_txt_Opacity ;
  towrite[2]= TransparentOpaque >> 8 ;
  towrite[3]= TransparentOpaque ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

void txt_Set(WORD  Func, WORD  Value)
{
  unsigned char  towrite[6] ;
  towrite[0]= F_txt_Set >> 8 ;
  towrite[1]= F_txt_Set ;
  towrite[2]= Func >> 8 ;
  towrite[3]= Func ;
  towrite[4]= Value >> 8 ;
  towrite[5]= Value ;
  WriteBytes(towrite, 6) ;
  GetAck() ;
}

WORD txt_Underline(WORD  Underline)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_Underline >> 8 ;
  towrite[1]= F_txt_Underline ;
  towrite[2]= Underline >> 8 ;
  towrite[3]= Underline ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD txt_Width(WORD  Multiplier)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_Width >> 8 ;
  towrite[1]= F_txt_Width ;
  towrite[2]= Multiplier >> 8 ;
  towrite[3]= Multiplier ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD txt_Wrap(WORD  Position)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_Wrap >> 8 ;
  towrite[1]= F_txt_Wrap ;
  towrite[2]= Position >> 8 ;
  towrite[3]= Position ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD txt_Xgap(WORD  Pixels)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_Xgap >> 8 ;
  towrite[1]= F_txt_Xgap ;
  towrite[2]= Pixels >> 8 ;
  towrite[3]= Pixels ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD txt_Ygap(WORD  Pixels)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_txt_Ygap >> 8 ;
  towrite[1]= F_txt_Ygap ;
  towrite[2]= Pixels >> 8 ;
  towrite[3]= Pixels ;
  WriteBytes(towrite, 4) ;
  return GetAckResp() ;
}

WORD writeString(WORD  Handle, unsigned char *  StringOut)
{
  unsigned char  towrite[4] ;
  towrite[0]= F_writeString >> 8 ;
  towrite[1]= F_writeString ;
  towrite[2]= Handle >> 8 ;
  towrite[3]= Handle ;
  WriteBytes(towrite, 4) ;
  WriteChars(StringOut) ;
  return GetAckResp() ;
}

/*
 * Conpound 4D Routines Ends here
*/


int OpenComm(char *sDeviceName, int newrate)
{
    struct termios new_port_settings;
    //WORD    nBaud;
    int k, ch, tSave, baudr;
    
switch(newrate)
  {
    case      50 : baudr = B50;         break;
    case      75 : baudr = B75;         break;
    case     110 : baudr = B110;        break;
    case     134 : baudr = B134;        break;
    case     150 : baudr = B150;        break;
    case     200 : baudr = B200;        break;
    case     300 : baudr = B300;        break;
    case     600 : baudr = B600;        break;
    case    1200 : baudr = B1200;       break;
    case    1800 : baudr = B1800;       break;
    case    2400 : baudr = B2400;       break;
    case    4800 : baudr = B4800;       break;
    case    9600 : baudr = B9600;       break;
    case   19200 : baudr = B19200;      break;
    case   38400 : baudr = B38400;      break;
    case   57600 : baudr = B57600;      break;
    case  115200 : baudr = B115200;     break;
    case  230400 : baudr = B230400;     break;
    case  460800 : baudr = B460800;     break;
    case  500000 : baudr = B500000;     break;
    case  576000 : baudr = B576000;     break;
    case  921600 : baudr = B921600;     break;
    case 1000000 : baudr = B1000000;    break;
    default      : printf("invalid baudrate\n");
                   return(1);
                   break;
}
    cPort = open(sDeviceName, O_RDWR | O_NOCTTY | O_NDELAY);
// Current config
    tcgetattr(cPort, &new_port_settings);
    // Set the line to RAW
    cfmakeraw(&new_port_settings);
    memset(&new_port_settings, 0, sizeof(new_port_settings));  /* clear the new struct */
    new_port_settings.c_cflag = baudr | CS8 | CLOCAL | CREAD;
    new_port_settings.c_lflag &= ~(ICANON | ECHO | ECHOE | ISIG);
    new_port_settings.c_iflag = IGNPAR;
    new_port_settings.c_oflag = 0;
    new_port_settings.c_lflag = 0;
    new_port_settings.c_cc[VMIN] = 0;      /* block untill n bytes are received */
    new_port_settings.c_cc[VTIME] = 1;     /* block untill a timer expires (n * 100 mSec.) */
/*
    cfsetospeed(&new_port_settings, nBaud);
    cfsetispeed(&new_port_settings, nBaud);
*/
    // set new config
    tcsetattr(cPort, TCSANOW, &new_port_settings);
    // Set non-blocking
    fcntl(cPort, F_SETFL, FNDELAY);
    
    tSave = TimeLimit4D;
    TimeLimit4D = 500;
    for (k = 0 ; k < 10 ; k++)
    {
        ch = 'X';
        write(cPort, (unsigned char *)&ch, 1);
        tcflush(cPort, TCOFLUSH);
        ReadSerPort((unsigned char *)&ch, 1);
        if (ch == 0x15)
            break ;
    }
    TimeLimit4D = tSave;

    tcflush(cPort, TCIOFLUSH);
    return 0;
}

void CloseComm(void)
{
    close(cPort);
    cPort = -1;
    Error4D = Err4D_OK;

    return;
}

